---
- hosts: all
  become: yes
  tasks:
  - name: Upgrade the OS
    apt:
      upgrade: dist
  - name: Install Google Chrome
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - name: Install packages via apt
    apt:
      name:
      - curl
      - python2
      - build-essential
      - gcc
      - libpng-dev
      - flameshot
      - net-tools
      - gnome-tweak-tool
      - asciinema
      - gstreamer1.0-libav
      state: present
      update_cache: yes
  - name: install packages via snap
    community.general.snap:
      name:
      - code
      - sublime-text
      - telegram-desktop
      classic: yes
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
